### ISSUE TITLE
Have a look at media breakpoints

### ISSUE THREAD

**Issue by dan-gamble** [onespacemedia/project-template#102]
Basically we have a problem at the moment in that our sites look pretty decent at 480, 768, 1024, 1440+ish and some points between but we do get quite a large amount of ranges where our sites just really don't work.

I think we should start taking a better approach towards responsive and start trying to work on fully responsive sites instead of selectively response sites.

https://medium.freecodecamp.com/the-100-correct-way-to-do-css-breakpoints-88d6a5ba1862#.v2qu87ucf is a pretty decent article on it and i think we need to decide on whether we should have different breakpoints for every project (So when the content starts to look a bit weird we add a breakpoint) or we do something along the lines of the article and use better ranges instead of "popular" device breakpoints.

**Comment by danielsamuels** [comment]
I like the breakpoints in that article.
