### ISSUE TITLE
Enable 'plain content' type by default

### ISSUE THREAD

**Issue by lewiscollard** [onespacemedia/project-template#103]
This seems to be used on every site, and I think it is useful for any site.

This will require renaming the commented-out 'Content' model to something else (as this is used by the sections app). and maybe renaming its `content_primary` field to just `text` or similar.

**Comment by danielsamuels** [comment]
Happy to change `content_primary` to `text`, but we'll leave it commented-out by default (primarily due to migrations).

**Comment by danielsamuels** [comment]
Comment out the CTA model and make it non-abstract.
