### ISSUE TITLE
Add a "page" link to the admin for each module

### ISSUE THREAD

**Issue by dan-gamble** [onespacemedia/project-template#115]
I find it a pain to find certain ContentBase's in the admin especially on a project i'm not overly familiar with.

I think it would be pretty decent to be able to create an admin from a mixin that just lists the pages of a certain ContentBase that sits under each app's admin. If it's singular it would take you straight to the edit page of that page otherwise list the ContentBase's available

**Comment by danielsamuels** [comment]
Add a `content_type` to the `list_filter` of the Pages app.
