### ISSUE TITLE
Add an include/template function for form fields

### ISSUE THREAD

**Issue by lewiscollard** [onespacemedia/project-template#130]
I'm thinking a `render_field(some_form_field)` or `{% include 'forms/form_field.html' %}`, which renders fields with our standard class names, so we can avoid boilerplate form classes that just add classes to inputs.

**Comment by dan-gamble** [comment]
I think a macros file with the standard `input` `select` `textarea` `checkbox` `radio` would be a good base to start with

**Comment by lewiscollard** [comment]
[This](https://gist.github.com/lewiscollard/68dbd3d4bbab8eb96601b892c02130de) might be a good start.

**Comment by danielsamuels** [comment]
Split field types into their own macros.  Could use 1.11's form template system to do it.

**Comment by danielsamuels** [comment]
We'll implement this in Cambridge Wireless and then port it into the project template.

**Comment by lewiscollard** [comment]
Fixed in #264
