### ISSUE TITLE
Handle images better

### ISSUE THREAD

**Issue by dan-gamble** [onespacemedia/project-template#134]
I think we could potentially come up with some kind of Vue component or JS snippet that emulates something like Medium.

https://thecoffeelicious.com/this-is-the-antidote-for-digital-narcissism-998b424a1ba1

You end up with HTML like:
```html
<figure name="4cb9" id="4cb9" class="graf graf--figure graf-after--p">
  <div class="aspectRatioPlaceholder is-locked" style="max-width: 550px; max-height: 496px;">
    <div class="aspectRatioPlaceholder-fill" style="padding-bottom: 90.2%;"></div>
    <div class="progressiveMedia js-progressiveMedia graf-image is-canvasLoaded is-imageLoaded" data-image-id="0*DE0XsDzUJvFtS95w.jpg" data-width="550" data-height="496" data-scroll="native">
      <img src="https://cdn-images-1.medium.com/freeze/max/30/0*DE0XsDzUJvFtS95w.jpg?q=20" crossorigin="anonymous" class="progressiveMedia-thumbnail js-progressiveMedia-thumbnail">
      <canvas class="progressiveMedia-canvas js-progressiveMedia-canvas" width="75" height="67"></canvas>
      <img class="progressiveMedia-image js-progressiveMedia-image" data-src="https://cdn-images-1.medium.com/max/800/0*DE0XsDzUJvFtS95w.jpg" src="https://cdn-images-1.medium.com/max/800/0*DE0XsDzUJvFtS95w.jpg">
      <noscript class="js-progressiveMedia-inner">&lt;img class="progressiveMedia-noscript js-progressiveMedia-inner" src="https://cdn-images-1.medium.com/max/800/0*DE0XsDzUJvFtS95w.jpg"&gt;</noscript>
    </div>
  </div>
</figure>
```

Few notes:

* They progressively load images
* They use the "Intrinsic" style to do images
* They don't blanket images with a singular aspect ratio, they use the uploaded sizes to do it

Advantages to this:

* Better page load times due to progressively loading images
* No layout shifting as they have the `aspectRatioPlaceholder-fill` to hold the size even when the image isn't loaded
* A much nicer overall experience.

I believe this could be achieved relatively easily with the `media` app change where it records the size on upload. We would also be able to supply aspect ratio props so we could ensure a certain ratio is followed on cards for example where everything needs to be uniformly styled.

Edit**
Link: https://jmperezperez.com/medium-image-progressive-loading-placeholder/

**Comment by danielsamuels** [comment]
What's the canvas used for?

**Comment by dan-gamble** [comment]
I believe that's used when the image is loaded. You'll see it goes: `nothing` => `blurred` => `image`. I think it's for the blurring stage as it's more cross browser compliant.
