### ISSUE TITLE
Freeze version numbers of Pylint in Circle

### ISSUE THREAD

**Issue by lewiscollard** [onespacemedia/project-template#136]
Because it's happened a few times wherein Circle always installs the latest version of Pylint, which may have new featured/errors but our local versions are frozen at the version we first installed. This causes code that builds fine in pre-commit/pre-push fails a build.

**Comment by danielsamuels** [comment]
Alternate choice: change circle.yml to run `pip install -U pylint [...]`

**Comment by dan-gamble** [comment]
I'd pin as if you do `pip install -U pylint` you could get a different pylint on circle that you do locally. I tend to install pylint right at the start of the project so the version i use for it is the one i use throughout.

**Comment by danielsamuels** [comment]
Why would you get a different version if you're always up-to-date with what's on pip?

**Comment by dan-gamble** [comment]
For example i started Owlstone 8 months ago, when i created that i did `pip install -r requirements.txt` and it installed Pylint 1. If i do a push for it today and the `circle.yml` line has `pip install -U pylint` it might install Pylint 17 while i'm still on 1. If we just pin it at the start of the project it ensures they are always the same.

**Comment by danielsamuels** [comment]
But every push would run `pip install -U pylint` on your local machine, and then it would run it on Circle, so both would be on 17?

**Comment by dan-gamble** [comment]
How would it run it locally?

**Comment by danielsamuels** [comment]
The pre-push hook runs it every time because it's reading from the circle.yml file.

**Comment by danielsamuels** [comment]
Though saying that, there's a line in the pre-push hook itself which runs `pip install`, that's the only one that needs updating.

**Comment by danielsamuels** [comment]
[This one here](https://github.com/onespacemedia/project-template/blob/5ab358c3523bfa34791e288782f1f9ebcfbcb7c3/%7B%7Bcookiecutter.repo_name%7D%7D/pre-push#L16) is what needs updating.

**Comment by dan-gamble** [comment]
I thought we were going to be moving to `pre-commit` instead of `pre-push`. Not sure how we could incorporate it in to `pre-commit` unless it ran it before `pylint` everytime

**Comment by dan-gamble** [comment]
I'd rather just pin at the start as changing linting rules halfway through a project would be a bit weird, it's what their latest release did.

**Comment by danielsamuels** [comment]
Freeze on the initially installed version, update default applications to match the new specification.

Look to update to latest version in future.

**Comment by danielsamuels** [comment]
I've just merged #150 which adds the pylint stuff to the requirements file.  I think we just need to remove the `pip install pylint` line from the circle.yml file for this to be resolved.

**Comment by dan-gamble** [comment]
Fixed in https://github.com/onespacemedia/project-template/commit/d2afa1cc1ce47a14616f26d7dbb7aa654d5f4e13
