### ISSUE TITLE
Changing the way to use VR as multiples

### ISSUE THREAD

**Issue by eikhunter** [onespacemedia/project-template#161]
Instead of working out what division of the line height we need, we work from the lowest baseline i.e. 8px is the baseline and then it works respectively, so 8px = 1vr 16px = 2vr etc etc, but it would need to find out a solution for when it's not easily divisible.

<img width="1055" alt="screen shot 2017-06-27 at 10 08 56" src="https://user-images.githubusercontent.com/19905000/27580507-b5b34dd8-5b22-11e7-9a07-2ca46944adb9.png">

**Comment by lewiscollard** [comment]
I agree with the core of the reasoning here - if you start accepting arbitrary fractions it becomes very easy to break the vertical rhythm. But it seems to me that starting with a significantly smaller baseline and multiplying it up seems like it'd have the same problem, though probably to a lesser extent. 24 pixels in one place and 32 in another doesn't feel like a vertical rhythm; that to me feels more "those things differ by 8 pixels".

**Comment by lewiscollard** [comment]
Fixed by the style guide. https://github.com/onespacemedia/styleguide#vertical-rhythm-and-the-vr-unit
