### ISSUE TITLE
Bring the email system into the template?

### ISSUE THREAD

**Issue by danielsamuels** [onespacemedia/project-template#169]
It seems like we're using it in almost every project recently, so perhaps it's worth promoting it into the PT?

**Comment by lewiscollard** [comment]
I think that is a good idea.

I don't think it's generally the best implementation of the system as a whole, but my most recent one does a good job of generating a passable plain-text version of the email with zero extra effort, so that bit might be worth stealing.

**Comment by danielsamuels** [comment]
I was considering making it work in the reverse way - dump your copy into a .txt file and then just `| linebreaks` the .txt file to create the HTML version. Would need some handling around links, but given that we generally receive the copy as plain text it might be easier to dump in.

**Comment by danielsamuels** [comment]
Actually, the best option is probably to use Markdown for the plain text version.  If you use the reference format for links it should translate well for both the plain text and HTML versions.

**Comment by danielsamuels** [comment]
Resolved in #191
