### ISSUE TITLE
Add custom 500 handler for template errors

### ISSUE THREAD

**Issue by jamesfoley** [onespacemedia/project-template#178]
Probably worth adding the custom handler500 from Cambridge Wireless which helps capture template errors which are usually invisible. Saves a lot of time picking apart templates.

https://github.com/onespacemedia/cambridge-wireless/blob/develop/cambridge_wireless/urls.py#L102

**Comment by lewiscollard** [comment]
Indirectly fixed by #273 / 6db95fafa240e.
