### ISSUE TITLE
Add CMS icons for common content types

### ISSUE THREAD

**Issue by lewiscollard** [onespacemedia/project-template#195]
Even on a relatively small project, the 'Add page' field has a bunch of identical icons. It would be nice if we could get some default icons for our most common `ContentBase` derivatives (and all of the project template apps).

![screen shot 2017-10-13 at 11 29 42](https://user-images.githubusercontent.com/4973097/31542411-c5e11cb2-b009-11e7-88e7-67845b16426d.png)

**Comment by danielsamuels** [comment]
https://github.com/onespacemedia/cms-icons ?

**Comment by lewiscollard** [comment]
How did I not think of that! I think I'm going to dry-run that on one of our current projects.
