### ISSUE TITLE
Fix JS paths for linting + precommit 

### ISSUE THREAD

**Issue by lewiscollard** [onespacemedia/project-template#197]
* `lint:js` checks `{{cookiecutter.package_name}}/assets/js/**/*.js`, which won't catch anything that sits directly in `assets/js` (e.g. `main.js`)
* `lint-staged` checks a different glob: `*.js`, which differs and will also catch changes on  `sections/templates/admin/pages/page/sections.js` (which causes a syntax error because it's a Django template)

**Comment by dan-gamble** [comment]
`lint:js` also needs to do an `eslint` check, currently it just runs `prettier`
