### ISSUE TITLE
Remove rule order from stylelint and add postcss-sorting

### ISSUE THREAD

**Issue by dan-gamble** [onespacemedia/project-template#22]

**Comment by danielsamuels** [comment]
Out of interest, what's the difference between the two?

**Comment by dan-gamble** [comment]
One makes you write the rule (Checks the order is in place and if it doesn't you need to change it to pass) the other automatically changes the files to suit.

Reason for wanting to potentially change to `postcss-sorting` is because of bugs with the rule order in Stylelint, `postcss-sorting` add's it's own problems though that i'd need to look at as well

**Comment by danielsamuels** [comment]
Is it not a good idea to maintain code style consistency though? Without stylelint you could write whatever code you want because "it will get fixed by postcss".

**Comment by dan-gamble** [comment]
That is a good point, all source code remains the same though. It sorts source code not the built code so when you save a file or commit it, it changes anyway.

I would prefer to use the stylelint way it's just causing multiple problems atm including #23 wheres it's not running on file save for some reason
