### ISSUE TITLE
Switch SMTP provider

### ISSUE THREAD

**Issue by danielsamuels** [onespacemedia/project-template#26]
Mandrill is going paid only. Look into alternatives. 

https://documentation.mailgun.com/quickstart-sending.html#verify-your-domain

**Comment by danielsamuels** [comment]
https://www.reddit.com/r/webdev/comments/47kh8z/some_recommendations_for_those_moving_away_from/

**Comment by danielsamuels** [comment]
Upon evaluation, we're going to go with [Mailjet](https://uk.mailjet.com/). The authentication details are static, so I'll get them updated in the base template.  For each project we will be required to verify the sending domain(s) we wish to use.  This doesn't take much effort, it's just a case of making a URL endpoint exist so that their checker can receive a 200 OK from requesting it.  The [cms-static-content](https://github.com/onespacemedia/cms-static-content) is the easiest method for making this possible, so we'll look to also make this an installable as part of the initial project creation.  I'll share the login details for Mailjet privately.

**Comment by yepher** [comment]
If you bump into issues with Mailjet here is the where the Mandrill migration to SparkPost [guide](https://www.sparkpost.com/mandrill-migration-guide) and this Slack channel is available if you need help with the migration 
    http://slack.sparkpost.com

**Comment by danielsamuels** [comment]
We've decided to just stick with Mandrill.
