### ISSUE TITLE
Make the JS file/directory structure consistent

### ISSUE THREAD

**Issue by lewiscollard** [onespacemedia/project-template#279]
I don't think there is anything wrong with the ways we are doing things, but I think there should be _one way_ of doing things and some consistent file structure. Some of the inconsistencies/things that I'm not big on:

* There's a bunch of stuff in `utils`, a name that implies helper functions, but has a bunch of stuff that are not helper functions at all. For example, the class list polyfill and `svg4everybody` and `webp-detector` aren't helpers, they're browser compatibility shims.
* Similarly in `utils/index.js` we mostly have helper functions, but there's also the `externalLinks` function, which is not.
* Why `site`? It seems like a strange name; by definition, everything is the `site`. (I know this is meant to be "site-specific stuff", but nearly everything gets modified to some extent to be site-specific.)
* On that note, why does some stuff live in `site` (like the navigation) and other stuff lives in its own directory (`viewport-animation/index.js`)?
* And on that note, in `main.js`, why do we use indirect imports in `site/` (the `index.js` therein exporting stuff from other files in that directory) but use direct imports elsewhere (e.g. `import { svg4everybody } from './utils/svgforeverybody'`)?

Any thoughts?

**Comment by AidanCurrah** [comment]
There is also stuff like `/images/index.js` has functions in it but `/site/index.js` simply passes navigation through

**Comment by lewiscollard** [comment]
That brings up another inconsistency; some functions take an element, and some things are just called and select the elements themselves. I am not sure which way I prefer.

**Comment by jin-park-dev** [comment]
How about these way to keep more consistent?

1. Create folder called "compatibility" for browser related compatibility files
- Class-list-polyfill
- Svgforeverybody.js
- Webp-detector.js

2. Regarding index.js

Have related js in it's own folder.
Have index.js as only to exports.
Have it's own file for related class / function.

3. Commonly used js such as "navigation", create it's own folder.
But more site specific js that's not always used create new folder "project-name".

**Comment by lewiscollard** [comment]
These are solid suggestions.

**Comment by joe-hastings** [comment]
@lewiscollard with passing the function an element I think the functions should just be called with no params and they handle getting their own elements or whatever they need, otherwise the functionality creeps out of the function/class like it has for Lazy image where a bunch of the logic for it is actually now in main.js, I think that stuff should probably be moved into image.js (or whatever it ends up being called as it should probably be called lazyimage.js)

**Comment by lewiscollard** [comment]
I can see the merit in either approach; your point is sound, but to me the other way also has its merits in that a function's purpose is a narrow 'do a thing to this element'.

**Comment by joe-hastings** [comment]
For functions within the classes I think its fine to pass an element to do something so the functions only do one job, but in main.js if it's including the LazyImage class it seems less desirable that the setting up is just in the main DOMContentLoaded function, rather than in some init style function in LazyImage class itself

**Comment by joe-hastings** [comment]
How do the following suggestions sound:

* `main.js` only has imports and initialisations of classes or functions, no logic
* Each folder has it's js in `index.js` for functions, classes get their own file with the filename same as the class name
* To handle how Lazy image currently has it's logic in `main.js`, have this logic in a function in `js/lazyimage/index.js` called something like `setUpLazyImages` to handle this set up, `lazyimage.js` would sit in the same directory containing the class itself
* Simple function based calls (cookie-bar, parallax, viewport-animation, wysiwyg, externalLinks) sit in `js/suitable-directory-name/index.js`, the directory name would be the same as the function name
* Current utils stuff uses Jin’s suggestion of `compatibility` folder that holds the shims

**Comment by joe-hastings** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [PT: Come up with a agreed structure for JS files](https://trello.com/c/oE3ZaxH7/29-pt-come-up-with-a-agreed-structure-for-js-files)

**Comment by joe-hastings** [comment]
Done in https://github.com/onespacemedia/project-template/commit/fa6add08913f4bad209a8c9c72e9bbb32418691d
