### ISSUE TITLE
Events app (LCFI)

### ISSUE THREAD

**Issue by dan-gamble** [onespacemedia/project-template#50]

**Comment by lewiscollard** [comment]
Parallax (PFP and others). This depends on me documenting it.

**Comment by danielsamuels** [comment]
WYSIWYG title classes in base settings.

**Comment by dan-gamble** [comment]
Simple contact page with form. Include always used fields like name, email, company, etc. And have the AJAX view.

**Comment by lewiscollard** [comment]
> WYSIWYG title classes in base settings.

Good idea. Plus stub classes in the WYSIWYG CSS?

WYSIWYG editor idea: can we make the default background colour in the admin white?

**Comment by lewiscollard** [comment]
@dan-gamble,

> Simple contact page with form. Include always used fields like name, email, company, etc. And have the AJAX view.

You may want to take a look at PFP's of this - it does AJAX and has a fully-functional non-JS fallback as well.

**Comment by dan-gamble** [comment]
Move previous / next objects onto the model instead of the view: (DG)
    ```
    def next_career(self):
        try:
            return self.get_next_by_date_posted()
        except Career.DoesNotExist:
            return Career.objects.order_by('-date_posted', '-pk').last()

    def prev_career(self):
        try:
            return self.get_previous_by_date_posted()
        except Career.DoesNotExist:
            return Career.objects.order_by('-date_posted', '-pk').first()
    ```

**Comment by dan-gamble** [comment]
JS to open all external links in a new window. See any project I've built recently (usually 'external-links.js' or 'external-links/index.js'. Latest version is in the resources repo (LC)

**Comment by dan-gamble** [comment]
Parallax (PFP and others). This depends on me documenting it. (LC)

**Comment by dan-gamble** [comment]
Call to action (Imperial Ventures)

**Comment by dan-gamble** [comment]
Partners app (LCFI)

**Comment by dan-gamble** [comment]
Animation system (LCFI)

**Comment by lewiscollard** [comment]
Idea: Resurrect the Intrinsic mixin.

Mostly because it saves typing this a dozen times:
```
.whatever {
  position: relative;

  &::before {
    content: '';


    display: block;
    padding-bottom: percentage(9, 16);
  }
}
```

**Comment by danielsamuels** [comment]
Make into `cms-events`.

**Comment by danielsamuels** [comment]
https://github.com/onespacemedia/cms-events
