### ISSUE TITLE
Resurrect the Intrinsic mixin.

### ISSUE THREAD

**Issue by dan-gamble** [onespacemedia/project-template#59]
Mostly because it saves typing this a dozen times:

```
.whatever {
  position: relative;

  &::before {
    content: '';


    display: block;
    padding-bottom: percentage(9, 16);
  }
}
```

**Comment by lewiscollard** [comment]
With this one approved: As we are going to have very few mixins in the base, and only for things that take parameters (this might even end up being the only one), should we just have a single `helpers/mixins.css` rather than resurrecting the `mixins` directory?

**Comment by danielsamuels** [comment]
Where can I get this from and where's the best place to put it?

**Comment by dan-gamble** [comment]
https://github.com/onespacemedia/owlstone-medical/blob/develop/owlstone/assets/css/helpers/mixins.css#L167

And i'd say this is the best place for it too a solo `mixins.css`

**Comment by dan-gamble** [comment]
Akin to `utils.js`

**Comment by lewiscollard** [comment]
On top of the above you'll need this:

https://github.com/onespacemedia/owlstone-medical/commit/a107a9c7b8a8549a04e637147b1d4a7338f2122c
