### ISSUE TITLE
Incorporate some macros that would appear on most projects

### ISSUE THREAD

**Issue by dan-gamble** [onespacemedia/project-template#75]
* Cards for example
* Certain sections could be here i.e. `hero`, `plain_hero`
* Call to action
* Certain lists

Maybe some of these can be broken out into the library repo for ones that won't necessarily appear on all builds but quite a few

**Comment by danielsamuels** [comment]
Yes, but need to determine which ones.

**Comment by danielsamuels** [comment]
Closing in favour of #121.
