### ISSUE TITLE
Mobile nav needs updating

### ISSUE THREAD

**Issue by dan-gamble** [onespacemedia/project-template#76]
* Make it 3 deep by default
* Bring it up to date with recent projects (Owlstone, Imperial LCFI)
* Normalise all styles instead of `Link`, `Child_Link`, `ChildChild_Link`

**Comment by danielsamuels** [comment]
I wonder if there's a better naming scheme that we could use? Perhaps something like `TierOne`, `TierTwo`, `TierThree` or something?

**Comment by dan-gamble** [comment]
That would work better but my normalisation comment was in regards to styles. `Child` and `ChildChild` tends to be the same but are duplicated. I've started normalising them recently to all just be `Child_Link` no matter how deep.
