### ISSUE TITLE
Add a Grid_Inside variable that controls horizontal spacing.

### ISSUE THREAD

**Issue by dan-gamble** [onespacemedia/project-template#79]
Assuming spacing inside a card or panel is `1hr` (What we normally would consider `calc(var(--Grid_Gutter) * 2);`

Basically from day dot i've always assumed `1hr` `===` `Grid_Gutter * 2` but after speaking to Chiara it seems `Grid_Gutter * 2` `!==` `1hr`. `1hr` is actually `===` `Grid_Inside * 2`.

I was led to believe the 1st scenario because our `Grid_Gutter` is normally `15` and the inside of cards are normally `15 *2`. On Owlstone the `Grid_Gutter` is `23` so naturally i assumed `1hr` == `46` but it turns out it's actually `40`, making another variable of `Grid_Inside`.

We could potentially just run `Grid_Inside` off of the `Grid_Gutter` by default then change either if we see fit.

If this gets added going forward all horizontal spacing should be done by `calc(var(--Grid_Inside) * 2)` instead of `calc(var(--Grid_Gutter) * 2)`. For the most part on projects the only thing that really changes here is when we write that as the `Grid_Gutter` and `Grid_Inside` variables are normally the same. But this change allows us to write the same code `calc(var(--Grid_Inside) * 2)` regardless of each's value.

**Comment by dan-gamble** [comment]
Another thought, we could potentially expand this further into a `postcss` plugin that would allow us to write `1hr` like in my examples above similar to how we write `1vr`. This could cut down a lot of code repetition.

**Comment by danielsamuels** [comment]
It might be worth also adding a shorthand version of `calc(var(blah) * 2)` at the same time, along the lines of:

```
--Grid_Gutter: 15px;
--Grid_Inside: --Grid_Gutter;
--GI2x: calc(var(--Grid_Inside) * 2);
```

**Comment by lewiscollard** [comment]
> Another though, we could potentially expand this further into a postcss plugin that would allow us to write 1hr like in my examples above similar to how we write 1vr. 

This would be excellent. Is the package that handles `vr` one of ours, and if so would it make sense to implement it therein?

**Comment by dan-gamble** [comment]
I added another comment about doing a plugin that would let us do `1hr`, that could be another option as well.

**Comment by dan-gamble** [comment]
Nah, the `vr` package is [postcss-lh](https://www.npmjs.com/package/postcss-lh). I could fork and add or create a seperate one as `hr` is basically a term i just made up where as `vr` is an actual design thing :D

**Comment by lewiscollard** [comment]
Maybe `1gm`, for Grid Margin?

**Comment by dan-gamble** [comment]
Tbf `Grid_inside` is probably a bad name for starters as the spacing as actually nothing to do with the grid. `Grid_Gutter` would be `gm`, not sure what the `Grid_Inside` equivalent would boil down to. I went for `hr` just for `horizontal rhythm` shortness but open to suggestions on that.

**Comment by lewiscollard** [comment]
I have no objection to `hr`. I can't think of anything else that clearly disambiguates it from the gutter around the grid.

**Comment by dan-gamble** [comment]
Aye, tis a tricky one. It'll just be an option anyway tbh so easily changed in the future. the `postcss-lh` default is `lh` and the option changes it to `vr`.

**Comment by dan-gamble** [comment]
This still needs the Postcss plugin written for it, so keeping it open

**Comment by lewiscollard** [comment]
Ah, my bad!
