### ISSUE TITLE
Add "used on" admin mixin

### ISSUE THREAD

**Issue by lewiscollard** [onespacemedia/project-template#82]
...for things in a `components` app, where you want to see the things on which they are in use in the `list_display`. I made an attempt at genericising this in Owlstone, but it could probably use some cleanup:

https://github.com/onespacemedia/owlstone-medical/blob/develop/owlstone/apps/utils/admin.py

This should probably have a check for the `sections` app being installed. (Is it ever not?)

**Comment by danielsamuels** [comment]
Put into `project/utils/admin.py` in this repo.

**Comment by danielsamuels** [comment]
Wrap [this line](https://github.com/onespacemedia/project-template/blob/develop/%7B%7Bcookiecutter.repo_name%7D%7D/%7B%7Bcookiecutter.package_name%7D%7D/utils/admin.py#L5) in a try / except, catching ImportError. In the except block define some dummy classes:

```
class ContentSection(object):
    pass
```

So the code still works, but the conditions will never be met.
