### ISSUE TITLE
Don't necessarily npm i on project start

### ISSUE THREAD

**Issue by dan-gamble** [onespacemedia/project-template#84]
https://github.com/onespacemedia/project-template/blob/develop/hooks/post_gen_project.sh#L73

Could be worth checking i yarn is installed and using that or just make it yarn always

**Comment by lewiscollard** [comment]
I think if we're all agreed that we like Yarn, and that Yarn seems to work fine with our setup, then as you say we should skip the check and just do `yarn` always.

**Comment by danielsamuels** [comment]
..and if it breaks because you don't have yarn installed, then you're an idiot and should install yarn. :)

**Comment by lewiscollard** [comment]
Talking of which, I should install Yarn!
