### ISSUE TITLE
Change header terms to those used in newspapers.

### ISSUE THREAD

**Issue by danielsamuels** [onespacemedia/project-template#93]
Currently we use "SuperTitle", "Title" and "Meta" to reference elements of most header blocks, but there are pre-existing terms which have been widely used in the print industry for some time. Those terms are "Kicker", "Headline" and "Byline"

![](http://f.tqn.com/y/desktoppub/1/W/O/2/4/KickerHeadlineDeckBylineDropCap.jpg)

This proposal is to switch our internal naming scheme to these pre-established terms.

**Comment by dan-gamble** [comment]
Is there anything that encompasses `_Text`?

**Comment by danielsamuels** [comment]
[Body text](http://image.guardian.co.uk/sys-files/Guardian/documents/2011/08/26/EducCentNewsterminology.pdf) by the looks of things.

**Comment by danielsamuels** [comment]
We'll close this when the guidance is in a style guide.
