### ISSUE TITLE
Change fonts into a mixin

### ISSUE THREAD

**Issue by dan-gamble** [onespacemedia/project-template#96]
Reasons for this

* Can incorporate all responsive styles into 1 thing, stops having to go through other classes to check how this font should be done.
* Encapsulates related things a lot better. If someone comes onto a project after someone else has done it they'll know what `font-weight`, `text-transform`, etc. are needed.

**Comment by danielsamuels** [comment]
Good:

```
@include FontGroup_44();
@include FontGroup_44-proxima();
```

Bad:

```
@include FontGroup_44(uppercase: true, family:proxima, weight:500);
```
