### ISSUE TITLE
Update password hashers to include Argon2

### ISSUE THREAD

**Issue by danielsamuels** [onespacemedia/project-template#99]
https://docs.djangoproject.com/en/1.10/topics/auth/passwords/#using-argon2-with-django

Support was added in 1.10, so we can either backport it (potentially dangerous?) or wait until the 1.11 LTS release.

**Comment by danielsamuels** [comment]
Waiting on onespacemedia/cms#126.

**Comment by lewiscollard** [comment]
Fixed by #200
